### ISSUE TITLE
How do I install this? 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [tigergraph/ecosys#130]
I read about a install.sh but can't find it. ... Thanks.

**Comment by HerkTG** [comment]
@LutzWeischerFujitsu Can you give us a few more details? Are you installing TigerGraph? Are you installing Algos? If you can walk us through the steps to provide context it will help us to help you.

**Comment by LutzWeischerFujitsu** [comment]
Installed libraries, did git clone. And now, how to compile / install it? Thanks.
