### ISSUE TITLE
操作TigerGraph的JDBC Driver？

### ISSUE THREAD

**Issue by KeViNOne** [tigergraph/ecosys#24]
ecosys/etl/tg-connect/com/tigergraph/connector/jdbc/路径里面的代码是从mysql读数据写入tigergraph的，请问有没有通过jdbc读写tigergraph的connector或者driver？

**Comment by TanYongSql** [comment]
Thanks for the comment. The new JDBC is ready now which could read from/write to TigerGraph.  It could also be used with Spark and Python.

Please check out [tg-jdbc-driver](https://github.com/tigergraph/ecosys/tree/master/etl/tg-jdbc-driver).
