### ISSUE TITLE
Built-in endpoint "POST /graph/{graph_name} - Upsert the given data" doesn't validate the request.

### ISSUE THREAD

**Issue by YuZhenXie** [tigergraph/ecosys#71]
- Edition: Developer
- Target built-in endpoint: [POST /graph/{graph_name} - Upsert the given data](https://docs.tigergraph.com/dev/restpp-api/built-in-endpoints#post-graph-graph_name-upsert-the-given-data)

As described in document, invalid source vertex type will cause the entire request to fail when upserting an edge. But when I tried with the invalid source vertex type, the edge still can be inserted. Please kindly confirm the issue. Thanks!!

**Comment by jonherke** [comment]
@YuZhenXie "invalid source vertex type" can you help me understand if this is what you meant:

Schema is as follows:
USER -(likes)-> MOVIE

Vertex Type in this case is USER, so if you type USERS (notice that I added an "S") that would be an "invalid source vertex type". 

So when you tried to do USERS the edge was created?

**Comment by YuZhenXie** [comment]
My case is different from the example you provided. Mine is like following.

Schema:
VERTEX USER
VERTEX EVENT
EDGE next_event (FROM EVENT, TO EVENT)  

When I upserted an `next_event` which is connected from USER to USER, the request is accepted and the edge is upserted. But the request should be rejected because USER is a "invalid source vertex type"..

**Comment by HerkTG** [comment]
Hi @YuZhenXie We just launched a new community site to answer these types of questions on https://community.tigergraph.com/. Please repost the original question there and someone will respond promptly. Thanks! Jon Herke, Technical Evangelist
