### ISSUE TITLE
time function datetime_format get error

### ISSUE THREAD

**Issue by 631068264** [tigergraph/ecosys#72]
```
CREATE QUERY test_demo(/* Parameters here */) FOR GRAPH traffic { 
  /* Write query logic here */ 
        STRING d = datetime_format(now(),"％Y-％m-％d％");
  PRINT d; 
}
```

![image](https://user-images.githubusercontent.com/8144089/77867195-d7265400-7268-11ea-9e27-0ddbf0e8c56c.png)

how to fix it

**Comment by HerkTG** [comment]
Hi @631068264  We just launched a new community site to answer these types of questions on https://community.tigergraph.com/. Please repost the original question there and someone will respond promptly. Thanks! Jon Herke, Technical Evangelist
