### ISSUE TITLE
unable to run JDBC examples

### ISSUE THREAD

**Issue by smcarik** [tigergraph/ecosys#74]
I have followed the instructions in the readme however when i try to run one of the 4 examples i get a ClassNotFound exception when it's trying to build the JDBC driver parent. specifically it says ClassNotFoundException: com.tigergraph.jdbc.examples.Builtins.  Any help would be greatly appreciated.

**Comment by TanYongSql** [comment]
Did the compilation succeed? Were you able to run the other 3 examples? Did you change to the "**tg-jdbc-examples**" directory before running the example? Does the following file exist?
`tg-jdbc-examples/target/classes/com/tigergraph/jdbc/examples/Builtins.class`

**Comment by smcarik** [comment]
I wasn't able to run any of the examples. and yes it compiled, and yes the Builtins.class existed.  However i just packaged the driver and created my own example and got it to work, so i guess i don't need an answer to this now, but thank you.

**Comment by smcarik** [comment]
no longer needed
