### ISSUE TITLE
Get jdbc response as JSONObject

### ISSUE THREAD

**Issue by smcarik** [tigergraph/ecosys#75]
When using the JDBC driver is it possible to have the response coming back be returned as a JSONObject rather than a result set?  Or at the very least is it possible to get the List of JSONObjects that is being passed to the constructor for the RestppResultSet class?  The way that we are using it would work best with the list of the json objects rather than as the result set in table form.

**Comment by HerkTG** [comment]
Hi @smcarik We just launched a new community site to answer these types of questions on https://community.tigergraph.com/. Please repost the original question there and someone will respond promptly. Thanks! Jon Herke, Technical Evangelist
