### ISSUE TITLE
function getvid not found

### ISSUE THREAD

**Issue by 4thfever** [tigergraph/ecosys#79]
Hi,
I created a brand new graph, and I copied your cycle_detection.gsql code from the Github page. I have a try on my platform and it says:

> The tuple name or the function getvid is not defined.

Could anyone please kindly tell me what the problem is？Thanks a lot

**Comment by jonherke** [comment]
@4thfever Can you provide a few screen captures to show us the errors. Also, please provide the schema and query (if possible)

**Comment by HerkTG** [comment]
Hi @4thfever We just launched a new community site to answer these types of questions on https://community.tigergraph.com/. Please repost the original question there and someone will respond promptly. Thanks! Jon Herke, Technical Evangelist
