### ISSUE TITLE
run interpreted query parse edge error

### ISSUE THREAD

**Issue by redloves** [tigergraph/ecosys#80]
when i use tg-jdbc-driver to run interpreted query in tigergraph 2.5.3, it'll tiger an error when execting RestppResultSet.parseEdge.because the interpreted query will return edges with out the attribute "attributes"

**Comment by HerkTG** [comment]
Hi @redloves  We just launched a new community site to answer these types of questions on https://community.tigergraph.com/. Please repost the original question there and someone will respond promptly. Thanks! Jon Herke, Technical Evangelist
