### ISSUE TITLE
Maven can not find the driver

### ISSUE THREAD

**Issue by sittingbool** [tigergraph/ecosys#82]
I cloned the repo, went to dir `ecosys/tools/etl/tg-jdbc-driver/tg-jdbc-examples` and ran a `mvn compile`

Which results in

` Failed to execute goal on project tg-jdbc-examples: Could not resolve dependencies for project com.tigergraph:tg-jdbc-examples:jar:1.2: Could not find artifact com.tigergraph:tg-jdbc-driver:jar:1.2 in central (https://repo.maven.apache.org/maven2)`

**Comment by jonherke** [comment]
@sittingbool Please compile JDBC at dir ecosys/tools/etl/tg-jdbc-driver/, instead of ecosys/tools/etl/tg-jdbc-driver/tg-jdbc-examples.

The latter is only used when running examples.

**Comment by HerkTG** [comment]
@sittingbool was this resolved?
