### ISSUE TITLE
elasticsearch idex how to be used in janusgraph benchmark？

### ISSUE THREAD

**Issue by andylulu** [tigergraph/ecosys#84]
i want to change backend to hbase and index to elasticsearch，and then to do it. so how to config graph500-janusgraph-cassandra.properties to finish this?

**Comment by HerkTG** [comment]
@andylulu Can you help me understand your question? Is this related to TigerGraph? We don't have tools and scripts for other platforms. If this is directly related to deploying or enabling a TigerGraph instance please re-add the issue with a clear concise problem statement and the outcome you are looking for us to address. Thanks!
